version: '3.8'

services:
  db:
    container_name: postgres-container
    image: postgres:15.7
    restart: always
    environment:
      POSTGRES_DB: shorturl
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432" 
  app:
    container_name: nest-container
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000" 
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/shorturl?schema=public
      SECRET: SECRET
      PORT: 3000
